### PR TITLE
upgrade maven plugins

### PR DESCRIPTION
**Pull request by caoxudong**
1. maven-resources-plugin (2.2 -> 2.7)
2. maven-shade-plugin     (1.2 -> 2.2)
3. maven-compiler-plugin  (2.0.2 -> 3.1, jdk 1.6 -> jdk 1.8)

For Maven 3.2.1 and Java 1.8.0_20, with the original pom configuration,
project cannot be packaged.Eclipse m2e doesn't support version 2.2 of
maven-resources-plugin. Besides, with version 2.0.2 of maven-compiler-plugin,
compilation failed.

So I upgrade these plugins.

### CODE REVIEW

**Comment by caoxudong** [comment]
Hi

After registering on Gerrit, what am I supposed to do next?

Thank you very much.

-caoxudong

2016-05-24 0:58 GMT+08:00 cb-sdk-robot <notifications@github.com>:

**Comment by mnunberg** [comment]
Did you sign the CLA there?

**Comment by caoxudong** [comment]
Hi

I have registerd gerrit with GitHub Account, and then clicked the link in
the letter( http://review.couchbase.org/#/settings/new-agreement), I saw
this,


​
Did I miss something?

Thank you very much.

-caoxudong

2016-06-03 22:55 GMT+08:00 M. Nunberg <notifications@github.com>:

**Comment by mnunberg** [comment]
@brett19 is the PR bot working on this one?

**Pull request closed without merging**
