### PR TITLE
Implement SCRAM SHA Authentication

### PR DESCRIPTION
**Pull request by SenolOzer1A**
CouchbaseMock delivered with support for SCRAM-SHA mode

### CODE REVIEW

**Comment by avsej** [comment]
Cool stuff, this is what I was going to do! I will be happy to review it and accept. Thanks @SenolOzer1A

**Comment by SenolOzer1A** [comment]
You're welcome. Let me know if you need explanation about the code.

**Comment by SenolOzer1A** [comment]
Hi Sergey, I have also created a pull request for couchbase-jvm-core. I have discovered a bug in SCRAM SHA authentication.

**Comment by avsej** [comment]
You'll better create the request directly on gerrit. We don't use github much. All review happens on http://review.couchbase.org/

**Comment by SenolOzer1A** [comment]
Ok. I have created the request on Gerrit.

**Pull request closed without merging**
